apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-deployment
  labels:
    app: capstone-project-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-project-app
  template:
    metadata:
      labels:
        app: capstone-project-app
    spec:
      containers:
        - name: capstone-project-app
          image: vijis/capstone-project
          ports:
            - containerPort: 80
       
